import{Router}from"express";import{randomUUID}from"node:crypto";import{sql}from"../db/neon.js";import{requireAuth}from"../middleware/auth.js";import{requireSuperAdmin}from"../middleware/superAdmin.js";
export const adminRouter=Router();adminRouter.use(requireAuth,requireSuperAdmin);
async function audit(req,action,resourceType,resourceId,details={}){await sql`insert into audit_log(actor_user_id,action,resource_type,resource_id,details) values(${req.user.id}::uuid,${action},${resourceType},${resourceId||null},${JSON.stringify(details)}::jsonb)`}
adminRouter.get("/summary",async(_req,res)=>{const[stores,users,orders,mrr]=await Promise.all([sql`select count(*)::int as n from stores where status in ('active','trial')`,sql`select count(*)::int as n from app_users where status='active'`,sql`select count(*)::int as n from orders where created_at>=date_trunc('day',now())`,sql`select coalesce(sum(p.monthly_price),0)::numeric as n from store_subscriptions s join plans p on p.id=s.plan_id where s.status='active'`]);const controls=await sql`select key,enabled,reason,updated_at from platform_controls order by key`;res.json({metrics:{stores:stores[0].n,users:users[0].n,orders_today:orders[0].n,mrr:Number(mrr[0].n)},controls})});
adminRouter.get("/stores",async(req,res)=>{const q=String(req.query.q||"").trim();const rows=q?await sql`select s.*,o.name as organization_name,ss.status as subscription_status,p.name as plan_name from stores s join organizations o on o.id=s.organization_id left join store_subscriptions ss on ss.store_id=s.id left join plans p on p.id=ss.plan_id where s.name ilike ${"%"+q+"%"} or s.slug ilike ${"%"+q+"%"} order by s.created_at desc limit 200`:await sql`select s.*,o.name as organization_name,ss.status as subscription_status,p.name as plan_name from stores s join organizations o on o.id=s.organization_id left join store_subscriptions ss on ss.store_id=s.id left join plans p on p.id=ss.plan_id order by s.created_at desc limit 200`;res.json({stores:rows})});
adminRouter.patch("/stores/:id",async(req,res)=>{const allowed=new Set(["active","trial","suspended","unpaid","maintenance","scheduled_for_deletion"]);const{status}=req.body||{};if(!allowed.has(status))return res.status(400).json({error:"Estado no permitido"});const rows=await sql`update stores set status=${status},updated_at=now() where id=${req.params.id}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Tienda no encontrada"});await audit(req,"store.status.updated","store",req.params.id,{status});res.json({store:rows[0]})});
adminRouter.get("/controls",async(_req,res)=>{const rows=await sql`select * from platform_controls order by key`;res.json({controls:rows})});
adminRouter.put("/controls/:key",async(req,res)=>{const{enabled,reason}=req.body||{};const rows=await sql`insert into platform_controls(key,enabled,reason,updated_at) values(${req.params.key},${Boolean(enabled)},${reason||null},now()) on conflict(key) do update set enabled=excluded.enabled,reason=excluded.reason,updated_at=now() returning *`;await audit(req,"platform.control.updated","platform_control",req.params.key,{enabled:Boolean(enabled),reason:reason||null});res.json({control:rows[0]})});
adminRouter.get("/plans",async(_req,res)=>{const rows=await sql`select * from plans order by monthly_price nulls last,name`;res.json({plans:rows})});
adminRouter.post("/plans",async(req,res)=>{const p=req.body||{};if(!p.name||!p.slug)return res.status(400).json({error:"Nombre y slug requeridos"});const rows=await sql`insert into plans(id,name,slug,status,monthly_price,annual_price,trial_days,is_public,metadata) values(${randomUUID()}::uuid,${p.name},${p.slug},${p.status||"active"},${p.monthly_price??null},${p.annual_price??null},${Number(p.trial_days||0)},${p.is_public!==false},${JSON.stringify(p.metadata||{})}::jsonb) returning *`;await audit(req,"plan.created","plan",rows[0].id,{name:p.name});res.status(201).json({plan:rows[0]})});
adminRouter.patch("/plans/:id",async(req,res)=>{const p=req.body||{};const rows=await sql`update plans set name=coalesce(${p.name||null},name),status=coalesce(${p.status||null},status),monthly_price=coalesce(${p.monthly_price??null},monthly_price),annual_price=coalesce(${p.annual_price??null},annual_price),trial_days=coalesce(${p.trial_days??null},trial_days),is_public=coalesce(${typeof p.is_public==="boolean"?p.is_public:null},is_public) where id=${req.params.id}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Plan no encontrado"});await audit(req,"plan.updated","plan",req.params.id,p);res.json({plan:rows[0]})});
adminRouter.get("/promotions",async(_req,res)=>{const rows=await sql`select * from promotions order by starts_at desc nulls last,code`;res.json({promotions:rows})});
adminRouter.post("/promotions",async(req,res)=>{const p=req.body||{};if(!p.code||!p.kind)return res.status(400).json({error:"Código y tipo requeridos"});const rows=await sql`insert into promotions(id,code,kind,value,free_months,starts_at,ends_at,max_uses,active,metadata) values(${randomUUID()}::uuid,${String(p.code).toUpperCase()},${p.kind},${p.value??null},${p.free_months??null},${p.starts_at||null}::timestamptz,${p.ends_at||null}::timestamptz,${p.max_uses??null},${p.active!==false},${JSON.stringify(p.metadata||{})}::jsonb) returning *`;await audit(req,"promotion.created","promotion",rows[0].id,{code:rows[0].code});res.status(201).json({promotion:rows[0]})});
adminRouter.get("/feature-flags",async(_req,res)=>{const rows=await sql`select * from platform_feature_flags order by key`;res.json({flags:rows})});
adminRouter.put("/feature-flags/:key",async(req,res)=>{const{enabled,rollout_percent=0,config={}}=req.body||{};const rows=await sql`insert into platform_feature_flags(key,enabled,rollout_percent,config,updated_at) values(${req.params.key},${Boolean(enabled)},${Math.max(0,Math.min(100,Number(rollout_percent)))},${JSON.stringify(config)}::jsonb,now()) on conflict(key) do update set enabled=excluded.enabled,rollout_percent=excluded.rollout_percent,config=excluded.config,updated_at=now() returning *`;await audit(req,"feature_flag.updated","feature_flag",req.params.key,rows[0]);res.json({flag:rows[0]})});
adminRouter.get("/audit",async(_req,res)=>{const rows=await sql`select a.*,u.email as actor_email from audit_log a left join app_users u on u.id=a.actor_user_id order by a.created_at desc limit 200`;res.json({audit:rows})});
