import{Router}from"express";import{randomUUID}from"node:crypto";import{sql}from"../db/neon.js";import{requireAuth}from"../middleware/auth.js";import{requireSuperAdmin}from"../middleware/superAdmin.js";
export const adminRouter=Router();adminRouter.use(requireAuth,requireSuperAdmin);
async function audit(req,action,resourceType,resourceId,details={}){const storeId=resourceType==="store"?resourceId:null;await sql`insert into audit_log(actor_user_id,actor_type,store_id,action,resource_type,resource_id,request_id,ip,user_agent,details) values(${req.user.id}::uuid,'super_admin',${storeId}::uuid,${action},${resourceType},${resourceId||null},${req.requestId||null},${req.ip||null},${req.get("user-agent")||null},${JSON.stringify(details)}::jsonb)`}
adminRouter.get("/summary",async(_req,res)=>{const[stores,users,orders,mrr]=await Promise.all([sql`select count(*)::int as n from stores where status in ('active','trial')`,sql`select count(*)::int as n from app_users where status='active'`,sql`select count(*)::int as n from orders where created_at>=date_trunc('day',now())`,sql`select coalesce(sum(p.monthly_price),0)::numeric as n from store_subscriptions s join plans p on p.id=s.plan_id where s.status='active' and s.complimentary_reason is null`]);const controls=await sql`select key,enabled,reason,updated_at from platform_controls order by key`;res.json({metrics:{stores:stores[0].n,users:users[0].n,orders_today:orders[0].n,mrr:Number(mrr[0].n)},controls})});
adminRouter.get("/users",async(_req,res)=>{const rows=await sql`select u.id,u.email,u.name,u.role,u.status,u.created_at,count(distinct sm.store_id)::int as stores from app_users u left join store_members sm on sm.user_id=u.id group by u.id order by u.created_at desc limit 250`;res.json({users:rows})});
adminRouter.get("/stores",async(req,res)=>{const q=String(req.query.q||"").trim();const rows=q?await sql`select s.*,o.name as organization_name,ss.status as subscription_status,p.name as plan_name from stores s join organizations o on o.id=s.organization_id left join store_subscriptions ss on ss.store_id=s.id left join plans p on p.id=ss.plan_id where s.name ilike ${"%"+q+"%"} or s.slug ilike ${"%"+q+"%"} order by s.created_at desc limit 200`:await sql`select s.*,o.name as organization_name,ss.status as subscription_status,p.name as plan_name from stores s join organizations o on o.id=s.organization_id left join store_subscriptions ss on ss.store_id=s.id left join plans p on p.id=ss.plan_id order by s.created_at desc limit 200`;res.json({stores:rows})});
adminRouter.patch("/stores/:id",async(req,res)=>{const allowed=new Set(["active","trial","suspended","unpaid","maintenance","scheduled_for_deletion"]);const{status}=req.body||{};if(!allowed.has(status))return res.status(400).json({error:"Estado no permitido"});const rows=await sql`update stores set status=${status},updated_at=now() where id=${req.params.id}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Tienda no encontrada"});await audit(req,"store.status.updated","store",req.params.id,{status});res.json({store:rows[0]})});
adminRouter.get("/controls",async(_req,res)=>{const rows=await sql`select * from platform_controls order by key`;res.json({controls:rows})});
adminRouter.put("/controls/:key",async(req,res)=>{const{enabled,reason}=req.body||{};const rows=await sql`insert into platform_controls(key,enabled,reason,updated_at) values(${req.params.key},${Boolean(enabled)},${reason||null},now()) on conflict(key) do update set enabled=excluded.enabled,reason=excluded.reason,updated_at=now() returning *`;await audit(req,"platform.control.updated","platform_control",req.params.key,{enabled:Boolean(enabled),reason:reason||null});res.json({control:rows[0]})});
adminRouter.get("/plans",async(_req,res)=>{const rows=await sql`select * from plans order by monthly_price nulls last,name`;res.json({plans:rows})});
adminRouter.post("/plans",async(req,res)=>{const p=req.body||{};if(!p.name||!p.slug)return res.status(400).json({error:"Nombre y slug requeridos"});const rows=await sql`insert into plans(id,name,slug,status,monthly_price,annual_price,trial_days,is_public,metadata) values(${randomUUID()}::uuid,${p.name},${p.slug},${p.status||"active"},${p.monthly_price??null},${p.annual_price??null},${Number(p.trial_days||0)},${p.is_public!==false},${JSON.stringify(p.metadata||{})}::jsonb) returning *`;await audit(req,"plan.created","plan",rows[0].id,{name:p.name});res.status(201).json({plan:rows[0]})});
adminRouter.patch("/plans/:id",async(req,res)=>{const p=req.body||{};const rows=await sql`update plans set name=coalesce(${p.name||null},name),status=coalesce(${p.status||null},status),monthly_price=case when ${Object.prototype.hasOwnProperty.call(p,"monthly_price")} then ${p.monthly_price??null} else monthly_price end,annual_price=case when ${Object.prototype.hasOwnProperty.call(p,"annual_price")} then ${p.annual_price??null} else annual_price end,trial_days=coalesce(${p.trial_days??null},trial_days),is_public=coalesce(${typeof p.is_public==="boolean"?p.is_public:null},is_public) where id=${req.params.id}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Plan no encontrado"});await audit(req,"plan.updated","plan",req.params.id,p);res.json({plan:rows[0]})});
adminRouter.get("/promotions",async(_req,res)=>{const rows=await sql`select * from promotions order by starts_at desc nulls last,code`;res.json({promotions:rows})});
adminRouter.post("/promotions",async(req,res)=>{const p=req.body||{};if(!p.code||!p.kind)return res.status(400).json({error:"Código y tipo requeridos"});const rows=await sql`insert into promotions(id,code,kind,value,free_months,starts_at,ends_at,max_uses,active,metadata) values(${randomUUID()}::uuid,${String(p.code).toUpperCase()},${p.kind},${p.value??null},${p.free_months??null},${p.starts_at||null}::timestamptz,${p.ends_at||null}::timestamptz,${p.max_uses??null},${p.active!==false},${JSON.stringify(p.metadata||{})}::jsonb) returning *`;await audit(req,"promotion.created","promotion",rows[0].id,{code:rows[0].code});res.status(201).json({promotion:rows[0]})});
adminRouter.get("/feature-flags",async(_req,res)=>{const rows=await sql`select * from platform_feature_flags order by key`;res.json({flags:rows})});
adminRouter.put("/feature-flags/:key",async(req,res)=>{const{enabled,rollout_percent=0,config={}}=req.body||{};const rows=await sql`insert into platform_feature_flags(key,enabled,rollout_percent,config,updated_at) values(${req.params.key},${Boolean(enabled)},${Math.max(0,Math.min(100,Number(rollout_percent)))},${JSON.stringify(config)}::jsonb,now()) on conflict(key) do update set enabled=excluded.enabled,rollout_percent=excluded.rollout_percent,config=excluded.config,updated_at=now() returning *`;await audit(req,"feature_flag.updated","feature_flag",req.params.key,rows[0]);res.json({flag:rows[0]})});
adminRouter.get("/health",async(_req,res)=>{const started=Date.now();try{const db=await sql`select now() as now`;const tables=await sql`select count(*)::int as n from information_schema.tables where table_schema='public'`;res.json({ok:true,api:"online",database:"online",database_time:db[0].now,table_count:tables[0].n,latency_ms:Date.now()-started})}catch(e){res.status(503).json({ok:false,api:"online",database:"unavailable",latency_ms:Date.now()-started})}});
adminRouter.get("/templates",async(_req,res)=>{const rows=await sql`select coalesce(theme->>'template','default') as template,count(*)::int as stores from store_theme group by coalesce(theme->>'template','default') order by stores desc,template`;res.json({templates:rows})});
adminRouter.get("/modules",async(_req,res)=>{const rows=await sql`select feature_key,count(*) filter(where enabled=true)::int as enabled_stores,count(*)::int as configured_stores from store_features group by feature_key order by feature_key`;res.json({modules:rows})});
adminRouter.get("/domains",async(_req,res)=>{const rows=await sql`select d.id,d.hostname,d.kind,d.status,d.verified_at,s.id as store_id,s.name as store_name,s.slug from domains d join stores s on s.id=d.store_id order by d.hostname limit 300`;res.json({domains:rows})});
adminRouter.get("/settings",async(_req,res)=>{const plans=await sql`select count(*)::int as n from plans where status='active' and is_public=true`;const stores=await sql`select count(*)::int as n from stores`;res.json({settings:{commercial_model:"paid_only",public_plans:plans[0].n,stores:stores[0].n,ai_policy:"premium_or_owner_grant"}})});
adminRouter.get("/audit",async(_req,res)=>{const rows=await sql`select a.*,u.email as actor_email from audit_log a left join app_users u on u.id=a.actor_user_id order by a.created_at desc limit 200`;res.json({audit:rows})});

adminRouter.get("/payment-accounts",async(req,res)=>{const q=String(req.query.q||"").trim();const rows=q?await sql`select s.id as store_id,s.name as store_name,s.slug,pa.provider,pa.provider_account_id,pa.status,pa.charges_enabled,pa.payouts_enabled,pa.details_submitted,pa.default_currency,pa.country,pa.updated_at from stores s left join store_payment_accounts pa on pa.store_id=s.id where s.name ilike ${"%"+q+"%"} or s.slug ilike ${"%"+q+"%"} order by pa.updated_at desc nulls last limit 200`:await sql`select s.id as store_id,s.name as store_name,s.slug,pa.provider,pa.provider_account_id,pa.status,pa.charges_enabled,pa.payouts_enabled,pa.details_submitted,pa.default_currency,pa.country,pa.updated_at from stores s left join store_payment_accounts pa on pa.store_id=s.id order by pa.updated_at desc nulls last limit 200`;res.json({payment_accounts:rows})});
adminRouter.get("/refunds",async(_req,res)=>{const rows=await sql`select r.id,r.order_id,r.amount,r.currency,r.status,r.reason,r.provider,r.provider_refund_id,r.created_at,r.processed_at,o.store_id,s.name as store_name,s.slug,o.order_number from order_refunds r join orders o on o.id=r.order_id join stores s on s.id=o.store_id order by r.created_at desc limit 200`;res.json({refunds:rows})});

adminRouter.put("/stores/:id/plan",async(req,res)=>{const slug=String(req.body?.plan||"").trim().toLowerCase();const plans=await sql`select id,name,slug from plans where slug=${slug} and status='active' limit 1`;if(!plans.length)return res.status(404).json({error:"Plan no encontrado"});const plan=plans[0];await sql`insert into store_subscriptions(store_id,plan_id,status,updated_at) values(${req.params.id}::uuid,${plan.id}::uuid,'active',now()) on conflict(store_id) do update set plan_id=excluded.plan_id,status='active',updated_at=now()`;await audit(req,"store.plan.updated","store",req.params.id,{plan:plan.slug});res.json({ok:true,plan})});
adminRouter.get("/access-codes",async(_req,res)=>{const rows=await sql`select a.*,p.slug as plan_slug,p.name as plan_name from access_codes a left join plans p on p.id=a.plan_id order by a.created_at desc limit 200`;res.json({access_codes:rows})});

adminRouter.post("/access-codes",async(req,res)=>{const p=req.body||{};const code=String(p.code||"").trim().toUpperCase();const allowedFeatures=new Set(["ai_assistant","ai_images","image_analysis"]);const grantType=p.grant_type||"feature";if(!code||!/^[A-Z0-9][A-Z0-9_-]{3,63}$/.test(code))return res.status(400).json({error:"Código no válido"});let planId=null;if(grantType==="feature"){if(!allowedFeatures.has(p.feature_key))return res.status(400).json({error:"Selecciona una función IA válida"})}else if(grantType==="plan"){const planSlug=String(p.plan||"").toLowerCase();if(!["basic","premium"].includes(planSlug))return res.status(400).json({error:"Selecciona Basic o Premium"});const planRows=await sql`select id from plans where slug=${planSlug} and status='active' limit 1`;if(!planRows.length)return res.status(404).json({error:"Plan no disponible"});planId=planRows[0].id}else return res.status(400).json({error:"Tipo de acceso no válido"});const id=randomUUID();const rows=await sql`insert into access_codes(id,code,name,grant_type,feature_key,plan_id,permanent,max_uses,active,complimentary_reason,complimentary_days) values(${id}::uuid,${code},${p.name||null},${grantType},${grantType==="feature"?p.feature_key:null},${planId}::uuid,${Boolean(p.permanent)},${p.max_uses??null},true,${p.complimentary_reason||"Concesión Super Admin"},${p.complimentary_days??null}) returning *`;await audit(req,"access_code.created","access_code",id,{code});res.status(201).json({access_code:rows[0]})});

adminRouter.patch("/access-codes/:id",async(req,res)=>{const enabled=Boolean(req.body?.active);const rows=await sql`update access_codes set active=${enabled} where id=${req.params.id}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Código no encontrado"});await audit(req,"access_code.updated","access_code",req.params.id,{active:enabled});res.json({access_code:rows[0]})});
