import{Router}from"express";import{randomUUID,scryptSync,timingSafeEqual}from"node:crypto";import{sql}from"../db/neon.js";import{clearSessionCookie,createSessionToken,sessionCookie}from"../auth/session.js";import{requireAuth}from"../middleware/auth.js";
export const authRouter=Router();
const hashPassword=p=>{const salt=randomUUID();const hash=scryptSync(p,salt,64).toString("hex");return salt+":"+hash};
const verify=(p,stored)=>{try{const[salt,hex]=stored.split(":");const a=Buffer.from(hex,"hex"),b=scryptSync(p,salt,64);return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}};
const superAdmins=()=>new Set(String(process.env.SUPER_ADMIN_EMAILS||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));
authRouter.get("/owner/status",async(_req,res)=>{const emails=[...superAdmins()];if(!emails.length)return res.json({configured:false,activated:false});const rows=await sql`select 1 from app_users where lower(email)=any(${emails}) and role='super_admin' and status='active' limit 1`;res.json({configured:true,activated:rows.length>0})});
authRouter.post("/owner/activate",async(req,res)=>{const{email,password,name}=req.body||{};const normalized=String(email||"").trim().toLowerCase();if(!superAdmins().has(normalized))return res.status(403).json({error:"Este correo no está autorizado como propietario"});if(!password||String(password).length<10)return res.status(400).json({error:"La contraseña debe tener al menos 10 caracteres"});const existing=await sql`select id,email,name,role,status from app_users where lower(email)=${normalized} limit 1`;let user;if(existing.length){if(existing[0].status!=="active")return res.status(403).json({error:"La cuenta está desactivada"});const rows=await sql`update app_users set password_hash=${hashPassword(password)},name=coalesce(${name||null},name),role='super_admin',updated_at=now() where id=${existing[0].id}::uuid returning id,email,name,role`;user=rows[0]}else{const rows=await sql`insert into app_users(id,email,password_hash,name,role) values(${randomUUID()}::uuid,${normalized},${hashPassword(password)},${name||"Propietario"},'super_admin') returning id,email,name,role`;user=rows[0]}const token=await createSessionToken(user);res.setHeader("Set-Cookie",sessionCookie(token));res.status(existing.length?200:201).json({user})});

authRouter.post("/register",async(req,res)=>{const{email,password,name}=req.body||{};if(!email||!password||password.length<8)return res.status(400).json({error:"Email y contraseña de 8+ caracteres requeridos"});const normalized=email.trim().toLowerCase();try{const id=randomUUID();const role=superAdmins().has(normalized)?"super_admin":"merchant";const rows=await sql`insert into app_users(id,email,password_hash,name,role) values(${id}::uuid,${normalized},${hashPassword(password)},${name||null},${role}) returning id,email,name,role`;const token=await createSessionToken(rows[0]);res.setHeader("Set-Cookie",sessionCookie(token));res.status(201).json({user:rows[0]})}catch(e){if(String(e).includes("unique"))return res.status(409).json({error:"Ese email ya existe"});throw e}});
authRouter.post("/login",async(req,res)=>{const{email,password}=req.body||{};const normalized=String(email||"").trim().toLowerCase();const rows=await sql`select id,email,name,role,status,password_hash from app_users where lower(email)=${normalized} limit 1`;if(!rows.length||rows[0].status!=="active"||!verify(password||"",rows[0].password_hash))return res.status(401).json({error:"Credenciales incorrectas"});const desiredRole=superAdmins().has(normalized)?"super_admin":rows[0].role;if(desiredRole!==rows[0].role)await sql`update app_users set role=${desiredRole},updated_at=now() where id=${rows[0].id}::uuid`;const user={id:rows[0].id,email:rows[0].email,name:rows[0].name,role:desiredRole};const token=await createSessionToken(user);res.setHeader("Set-Cookie",sessionCookie(token));res.json({user})});
authRouter.post("/logout",(_req,res)=>{res.setHeader("Set-Cookie",clearSessionCookie());res.status(204).end()});
authRouter.get("/me",requireAuth,async(req,res)=>{const rows=await sql`select id,email,name,role,status from app_users where id=${req.user.id}::uuid and status='active'`;res.json({user:rows[0]||null})});