import{Router}from"express";import{randomUUID}from"node:crypto";import{sql}from"../db/neon.js";import{requireAuth,requireStore}from"../middleware/auth.js";
export const commerceRouter=Router({mergeParams:true});commerceRouter.use(requireAuth,requireStore);

commerceRouter.get("/products",async(req,res)=>{const rows=await sql`select * from products where store_id=${req.storeId}::uuid order by created_at desc`;res.json({products:rows})});
commerceRouter.get("/products/:id",async(req,res)=>{const rows=await sql`select * from products where id=${req.params.id}::uuid and store_id=${req.storeId}::uuid limit 1`;if(!rows.length)return res.status(404).json({error:"Producto no encontrado"});const variants=await sql`select v.*,i.quantity,i.reserved,i.track_inventory,i.allow_backorder from product_variants v left join inventory_levels i on i.variant_id=v.id where v.product_id=${req.params.id}::uuid order by v.created_at`;const media=await sql`select m.*,pm.position,pm.is_primary from product_media pm join media_assets m on m.id=pm.media_id where pm.product_id=${req.params.id}::uuid order by pm.position`;const categories=await sql`select category_id from product_categories where product_id=${req.params.id}::uuid`;res.json({product:{...rows[0],variants,media,categories:categories.map(x=>x.category_id)}})});
commerceRouter.post("/products",async(req,res)=>{const p=req.body||{};if(!p.name||!p.slug)return res.status(400).json({error:"Nombre y slug requeridos"});const id=randomUUID();const rows=await sql`insert into products(id,store_id,name,slug,description,price,status,product_type,vendor,metadata,seo) values(${id}::uuid,${req.storeId}::uuid,${p.name},${p.slug},${p.description||""},${Number(p.price||0)},${p.status||"draft"},${p.product_type||null},${p.vendor||null},${JSON.stringify(p.metadata||{})}::jsonb,${JSON.stringify(p.seo||{})}::jsonb) returning *`;res.status(201).json({product:rows[0]})});
commerceRouter.put("/products/:id",async(req,res)=>{const p=req.body||{};const rows=await sql`update products set name=${p.name},slug=${p.slug},description=${p.description||""},price=${Number(p.price||0)},status=${p.status||"draft"},product_type=${p.product_type||null},vendor=${p.vendor||null},metadata=${JSON.stringify(p.metadata||{})}::jsonb,seo=${JSON.stringify(p.seo||{})}::jsonb,updated_at=now() where id=${req.params.id}::uuid and store_id=${req.storeId}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Producto no encontrado"});res.json({product:rows[0]})});

commerceRouter.get("/categories",async(req,res)=>{const rows=await sql`select * from categories where store_id=${req.storeId}::uuid order by position,name`;res.json({categories:rows})});
commerceRouter.post("/categories",async(req,res)=>{const c=req.body||{};if(!c.name||!c.slug)return res.status(400).json({error:"Nombre y slug requeridos"});const rows=await sql`insert into categories(id,store_id,name,slug,description,parent_id,position,active) values(${randomUUID()}::uuid,${req.storeId}::uuid,${c.name},${c.slug},${c.description||""},${c.parent_id||null}::uuid,${Number(c.position||0)},${c.active!==false}) returning *`;res.status(201).json({category:rows[0]})});

commerceRouter.post("/products/:id/variants",async(req,res)=>{const exists=await sql`select 1 from products where id=${req.params.id}::uuid and store_id=${req.storeId}::uuid`;if(!exists.length)return res.status(404).json({error:"Producto no encontrado"});const v=req.body||{};const rows=await sql`insert into product_variants(id,product_id,sku,title,price,compare_at_price,options,active) values(${randomUUID()}::uuid,${req.params.id}::uuid,${v.sku||null},${v.title||"Default"},${v.price===""?null:Number(v.price)},${v.compare_at_price?Number(v.compare_at_price):null},${JSON.stringify(v.options||{})}::jsonb,${v.active!==false}) returning *`;res.status(201).json({variant:rows[0]})});
commerceRouter.put("/products/:productId/variants/:variantId",async(req,res)=>{const v=req.body||{};const rows=await sql`update product_variants pv set sku=${v.sku||null},title=${v.title||"Default"},price=${v.price===""?null:Number(v.price)},compare_at_price=${v.compare_at_price?Number(v.compare_at_price):null},options=${JSON.stringify(v.options||{})}::jsonb,active=${v.active!==false} from products p where pv.id=${req.params.variantId}::uuid and pv.product_id=${req.params.productId}::uuid and p.id=pv.product_id and p.store_id=${req.storeId}::uuid returning pv.*`;if(!rows.length)return res.status(404).json({error:"Variante no encontrada"});res.json({variant:rows[0]})});
commerceRouter.put("/variants/:variantId/inventory",async(req,res)=>{const i=req.body||{};const owns=await sql`select 1 from product_variants v join products p on p.id=v.product_id where v.id=${req.params.variantId}::uuid and p.store_id=${req.storeId}::uuid`;if(!owns.length)return res.status(404).json({error:"Variante no encontrada"});const rows=await sql`insert into inventory_levels(variant_id,quantity,reserved,track_inventory,allow_backorder,updated_at) values(${req.params.variantId}::uuid,${Math.max(0,Number(i.quantity||0))},0,${i.track_inventory!==false},${Boolean(i.allow_backorder)},now()) on conflict(variant_id) do update set quantity=excluded.quantity,track_inventory=excluded.track_inventory,allow_backorder=excluded.allow_backorder,updated_at=now() returning *`;res.json({inventory:rows[0]})});

commerceRouter.put("/products/:id/media",async(req,res)=>{const ids=[...new Set((req.body?.media_ids||[]).slice(0,20))];const owns=await sql`select 1 from products where id=${req.params.id}::uuid and store_id=${req.storeId}::uuid`;if(!owns.length)return res.status(404).json({error:"Producto no encontrado"});if(ids.length){const valid=await sql`select id from media_assets where store_id=${req.storeId}::uuid and id=any(${ids}::uuid[])`;if(valid.length!==ids.length)return res.status(400).json({error:"Una o más imágenes no pertenecen a esta tienda"})}await sql`delete from product_media where product_id=${req.params.id}::uuid`;for(let position=0;position<ids.length;position++)await sql`insert into product_media(product_id,media_id,position,is_primary) values(${req.params.id}::uuid,${ids[position]}::uuid,${position},${position===0})`;const media=await sql`select m.*,pm.position,pm.is_primary from product_media pm join media_assets m on m.id=pm.media_id where pm.product_id=${req.params.id}::uuid order by pm.position`;res.json({media})});

commerceRouter.get("/orders",async(req,res)=>{const rows=await sql`select * from orders where store_id=${req.storeId}::uuid order by created_at desc limit 200`;res.json({orders:rows})});
commerceRouter.get("/customers",async(req,res)=>{const rows=await sql`select * from customers where store_id=${req.storeId}::uuid order by created_at desc limit 200`;res.json({customers:rows})});