import{Router}from"express";import{randomUUID}from"node:crypto";import{sql}from"../db/neon.js";import{requireAuth,requireStore}from"../middleware/auth.js";import{codeRedemptionLimiter}from"../middleware/rateLimit.js";import{requirePermission}from"../middleware/permissions.js";
export const storesRouter=Router();storesRouter.use(requireAuth);
const SLUG=/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;
const AI_FEATURE_KEYS=new Set(["ai_assistant","ai_images","image_analysis"]);const FEATURE_KEYS=new Set(["catalog","cart","checkout","orders","inventory","customers","coupons","wishlist","gift_cards","reservations","subscriptions","pos","blog","marketing","automations","b2b"]);
const RESERVED=new Set(["www","api","admin","app","support","status","mail","cdn","assets","static","dashboard","billing","auth","login","register","help","ftp","pop","smtp","autoconfig","store","stores","shop","checkout","webhook","webhooks","docs","developer","developers","dev","staging","test","internal","root","security","contact","notifications","imap","pop3","ns1","ns2","mx","email","media","images","files","uploads","download","downloads","public","private","system","platform"]);
storesRouter.get("/",async(req,res)=>{const rows=await sql`select s.*,sm.role,coalesce(ss.settings,'{}'::jsonb) as settings,coalesce(st.theme,'{}'::jsonb) as theme from stores s join store_members sm on sm.store_id=s.id left join store_settings ss on ss.store_id=s.id left join store_theme st on st.store_id=s.id where sm.user_id=${req.user.id}::uuid and sm.status='active' order by s.created_at desc`;res.json({stores:rows})});
storesRouter.post("/",async(req,res)=>{
 const{name,slug,sector,theme={},settings={},features=[]}=req.body||{};
 const baseSlug=String(slug||"").trim().toLowerCase();
 if(!name||!SLUG.test(baseSlug)||RESERVED.has(baseSlug))return res.status(400).json({error:"Nombre y subdominio válido requeridos"});
 const cleanFeatures=[...new Set(Array.isArray(features)?features:[])].filter(x=>FEATURE_KEYS.has(x)&&!AI_FEATURE_KEYS.has(x));
 const country=/^[A-Z]{2}$/.test(String(settings?.country||"").toUpperCase())?String(settings.country).toUpperCase():null;
 const currency=/^[A-Z]{3}$/.test(String(settings?.currency||"").toUpperCase())?String(settings.currency).toUpperCase():"EUR";
 for(let attempt=0;attempt<25;attempt++){
  const suffix=attempt===0?"":"-"+(attempt+1);
  const maxBase=63-suffix.length;
  const candidate=baseSlug.slice(0,maxBase).replace(/-+$/,"")+suffix;
  if(RESERVED.has(candidate))continue;
  const orgId=randomUUID(),storeId=randomUUID();
  const queries=[
   sql`insert into organizations(id,name) values(${orgId}::uuid,${String(name).trim()})`,
   sql`insert into stores(id,organization_id,name,slug,sector,status) values(${storeId}::uuid,${orgId}::uuid,${String(name).trim()},${candidate},${sector||null},'trial')`,
   sql`insert into store_members(store_id,user_id,role) values(${storeId}::uuid,${req.user.id}::uuid,'owner')`,
   sql`insert into store_settings(store_id,settings) values(${storeId}::uuid,${JSON.stringify(settings)}::jsonb)`,
   sql`insert into store_theme(store_id,theme) values(${storeId}::uuid,${JSON.stringify(theme)}::jsonb)`,
   sql`insert into store_payment_accounts(store_id,provider,status,country,default_currency) values(${storeId}::uuid,'stripe','not_connected',${country},${currency})`,
   ...cleanFeatures.map(feature=>sql`insert into store_features(store_id,feature_key,enabled) values(${storeId}::uuid,${feature},true)`)
  ];
  try{
   await sql.transaction(queries);
   return res.status(201).json({store:{id:storeId,name:String(name).trim(),slug:candidate,sector:sector||null,status:"trial",role:"owner",settings:settings||{},theme:theme||{},features:cleanFeatures.map(feature=>({feature_key:feature,enabled:true}))}});
  }catch(e){
   if(String(e).toLowerCase().includes("unique")&&attempt<24)continue;
   throw e;
  }
 }
 return res.status(409).json({error:"No se pudo reservar un subdominio disponible"});
});
storesRouter.put("/:storeId/payments/preferences",requireStore,requirePermission("payments.manage"),async(req,res)=>{const country=String(req.body?.country||"").trim().toUpperCase();const currency=String(req.body?.default_currency||"").trim().toUpperCase();if(!/^[A-Z]{2}$/.test(country)||!/^[A-Z]{3}$/.test(currency))return res.status(400).json({error:"País o divisa inválidos"});await sql`insert into store_payment_accounts(store_id,provider,status,country,default_currency) values(${req.storeId}::uuid,'stripe','not_connected',${country},${currency}) on conflict(store_id) do update set country=excluded.country,default_currency=excluded.default_currency,updated_at=now()`;res.json({ok:true,country,default_currency:currency})});
storesRouter.post("/:storeId/payments/connect",requireStore,requirePermission("payments.manage"),async(req,res)=>{
 if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({error:"Stripe todavía no está configurado en BravoShop"});
 const Stripe=(await import("stripe")).default;const stripe=new Stripe(process.env.STRIPE_SECRET_KEY);
 let rows=await sql`select provider_account_id,country,default_currency from store_payment_accounts where store_id=${req.storeId}::uuid limit 1`;
 if(!rows.length){
  const fallback=await sql`select ss.settings from store_settings ss where ss.store_id=${req.storeId}::uuid limit 1`;
  const country=/^[A-Z]{2}$/.test(String(fallback[0]?.settings?.country||"").toUpperCase())?String(fallback[0].settings.country).toUpperCase():null;
  const currency=/^[A-Z]{3}$/.test(String(fallback[0]?.settings?.currency||"").toUpperCase())?String(fallback[0].settings.currency).toUpperCase():"EUR";
  rows=await sql`insert into store_payment_accounts(store_id,provider,status,country,default_currency) values(${req.storeId}::uuid,'stripe','not_connected',${country},${currency}) on conflict(store_id) do update set updated_at=now() returning provider_account_id,country,default_currency`;
 }
 let accountId=rows[0]?.provider_account_id;
 if(!accountId){
  if(!rows[0]?.country)return res.status(400).json({error:"Configura el país de la cuenta antes de conectar Stripe"});
  const account=await stripe.accounts.create({type:"express",country:rows[0].country,capabilities:{card_payments:{requested:true},transfers:{requested:true}},metadata:{bravoshop_store_id:String(req.storeId)}},{idempotencyKey:`bravoshop-connect-${req.storeId}`});
  accountId=account.id;
  await sql`update store_payment_accounts set provider_account_id=${accountId},status='onboarding',country=coalesce(${account.country||null},country),updated_at=now() where store_id=${req.storeId}::uuid`;
 }
 const origin=String(process.env.FRONTEND_ORIGIN||"https://app.bravoshop.online").split(",")[0];
 const link=await stripe.accountLinks.create({account:accountId,refresh_url:origin+"/?payments=refresh",return_url:origin+"/?payments=return",type:"account_onboarding"});
 res.json({url:link.url});
});
storesRouter.post("/:storeId/payments/sync",requireStore,requirePermission("payments.manage"),async(req,res)=>{const rows=await sql`select provider_account_id from store_payment_accounts where store_id=${req.storeId}::uuid limit 1`;if(!rows[0]?.provider_account_id)return res.status(404).json({error:"Cuenta Stripe no conectada"});if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({error:"Stripe todavía no está configurado en BravoShop"});const Stripe=(await import("stripe")).default;const stripe=new Stripe(process.env.STRIPE_SECRET_KEY);const a=await stripe.accounts.retrieve(rows[0].provider_account_id);const status=a.charges_enabled&&a.payouts_enabled?"active":a.details_submitted?"restricted":"onboarding";await sql`update store_payment_accounts set status=${status},charges_enabled=${Boolean(a.charges_enabled)},payouts_enabled=${Boolean(a.payouts_enabled)},details_submitted=${Boolean(a.details_submitted)},default_currency=coalesce(${a.default_currency?.toUpperCase()||null},default_currency),country=coalesce(${a.country||null},country),updated_at=now() where store_id=${req.storeId}::uuid`;res.json({ok:true,status,charges_enabled:Boolean(a.charges_enabled),payouts_enabled:Boolean(a.payouts_enabled),details_submitted:Boolean(a.details_submitted)})});
storesRouter.get("/:storeId/payments",requireStore,requirePermission("payments.read"),async(req,res)=>{
 const rows=await sql`select provider,status,provider_account_id,charges_enabled,payouts_enabled,details_submitted,default_currency,country from store_payment_accounts where store_id=${req.storeId}::uuid limit 1`;
 if(rows.length)return res.json({payment_account:rows[0]});
 const fallback=await sql`select settings from store_settings where store_id=${req.storeId}::uuid limit 1`;
 res.json({payment_account:{provider:"stripe",status:"not_connected",provider_account_id:null,charges_enabled:false,payouts_enabled:false,details_submitted:false,default_currency:fallback[0]?.settings?.currency||"EUR",country:fallback[0]?.settings?.country||null}});
});
storesRouter.get("/:storeId",requireStore,requirePermission("store.read"),async(req,res)=>{const rows=await sql`select s.*,ss.settings,st.theme from stores s left join store_settings ss on ss.store_id=s.id left join store_theme st on st.store_id=s.id where s.id=${req.storeId}::uuid`;if(!rows.length)return res.status(404).json({error:"Tienda no encontrada"});const features=await sql`select feature_key,enabled,config from store_features where store_id=${req.storeId}::uuid`;res.json({store:{...rows[0],features}})});
storesRouter.patch("/:storeId",requireStore,requirePermission("store.update"),async(req,res)=>{const{name,sector,theme,settings}=req.body||{};if(name!==undefined&&(!String(name).trim()||String(name).trim().length>120))return res.status(400).json({error:"Nombre de tienda inválido"});await sql.transaction([...(name!==undefined||sector!==undefined?[sql`update stores set name=coalesce(${name===undefined?null:String(name).trim()},name),sector=coalesce(${sector===undefined?null:sector},sector),updated_at=now() where id=${req.storeId}::uuid`]:[]),...(settings!==undefined?[sql`insert into store_settings(store_id,settings) values(${req.storeId}::uuid,${JSON.stringify(settings||{})}::jsonb) on conflict(store_id) do update set settings=excluded.settings`]:[]),...(theme!==undefined?[sql`insert into store_theme(store_id,theme) values(${req.storeId}::uuid,${JSON.stringify(theme||{})}::jsonb) on conflict(store_id) do update set theme=excluded.theme`]:[])]);res.json({ok:true})});
storesRouter.put("/:storeId/features",requireStore,requirePermission("store.update"),async(req,res)=>{const features=Array.isArray(req.body?.features)?req.body.features:[];const clean=[...new Set(features)].filter(x=>FEATURE_KEYS.has(x)&&!AI_FEATURE_KEYS.has(x));const queries=[sql`update store_features set enabled=false where store_id=${req.storeId}::uuid`,...clean.map(feature=>sql`insert into store_features(store_id,feature_key,enabled) values(${req.storeId}::uuid,${feature},true) on conflict(store_id,feature_key) do update set enabled=true`)];await sql.transaction(queries);res.json({features:clean})});

storesRouter.get("/:storeId/shipping",requireStore,requirePermission("shipping.read"),async(req,res)=>{const zones=await sql`select z.*,coalesce(json_agg(json_build_object('id',r.id,'name',r.name,'price',r.price,'free_over',r.free_over,'min_days',r.min_days,'max_days',r.max_days,'active',r.active)) filter(where r.id is not null),'[]') as rates from shipping_zones z left join shipping_rates r on r.zone_id=z.id and r.store_id=z.store_id where z.store_id=${req.storeId}::uuid group by z.id order by z.created_at`;res.json({zones})});
storesRouter.post("/:storeId/shipping/zones",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const p=req.body||{};if(!String(p.name||"").trim())return res.status(400).json({error:"Nombre requerido"});const countries=[...new Set((Array.isArray(p.countries)?p.countries:[]).map(x=>String(x).toUpperCase()).filter(x=>/^[A-Z]{2}$/.test(x)))];const rows=await sql`insert into shipping_zones(store_id,name,countries) values(${req.storeId}::uuid,${String(p.name).trim()},${countries}) returning *`;res.status(201).json({zone:rows[0]})});
storesRouter.post("/:storeId/shipping/zones/:zoneId/rates",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const p=req.body||{};const zone=await sql`select id from shipping_zones where id=${req.params.zoneId}::uuid and store_id=${req.storeId}::uuid`;if(!zone.length)return res.status(404).json({error:"Zona no encontrada"});const price=Number(p.price||0),free=p.free_over==null||p.free_over===""?null:Number(p.free_over),min=p.min_days==null||p.min_days===""?null:Number(p.min_days),max=p.max_days==null||p.max_days===""?null:Number(p.max_days);if(!String(p.name||"").trim()||!Number.isFinite(price)||price<0||free!==null&&(!Number.isFinite(free)||free<0)||min!==null&&(!Number.isInteger(min)||min<0)||max!==null&&(!Number.isInteger(max)||max<0)||(min!==null&&max!==null&&max<min))return res.status(400).json({error:"Tarifa inválida"});const rows=await sql`insert into shipping_rates(zone_id,store_id,name,price,free_over,min_days,max_days) values(${req.params.zoneId}::uuid,${req.storeId}::uuid,${String(p.name).trim()},${price},${free},${min},${max}) returning *`;res.status(201).json({rate:rows[0]})});
storesRouter.patch("/:storeId/shipping/zones/:zoneId",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const p=req.body||{};const rows=await sql`update shipping_zones set name=coalesce(${p.name==null?null:String(p.name).trim()},name),countries=coalesce(${Array.isArray(p.countries)?[...new Set(p.countries.map(x=>String(x).toUpperCase()).filter(x=>/^[A-Z]{2}$/.test(x)))]:null},countries),active=coalesce(${p.active==null?null:Boolean(p.active)},active) where id=${req.params.zoneId}::uuid and store_id=${req.storeId}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Zona no encontrada"});res.json({zone:rows[0]})});
storesRouter.delete("/:storeId/shipping/zones/:zoneId",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const rows=await sql`delete from shipping_zones where id=${req.params.zoneId}::uuid and store_id=${req.storeId}::uuid returning id`;if(!rows.length)return res.status(404).json({error:"Zona no encontrada"});res.status(204).end()});
storesRouter.patch("/:storeId/shipping/rates/:rateId",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const p=req.body||{};const rows=await sql`update shipping_rates set name=coalesce(${p.name==null?null:String(p.name).trim()},name),price=coalesce(${p.price==null?null:Number(p.price)},price),free_over=case when ${Object.prototype.hasOwnProperty.call(p,"free_over")} then ${p.free_over==null||p.free_over===""?null:Number(p.free_over)} else free_over end,min_days=case when ${Object.prototype.hasOwnProperty.call(p,"min_days")} then ${p.min_days==null||p.min_days===""?null:Number(p.min_days)} else min_days end,max_days=case when ${Object.prototype.hasOwnProperty.call(p,"max_days")} then ${p.max_days==null||p.max_days===""?null:Number(p.max_days)} else max_days end,active=coalesce(${p.active==null?null:Boolean(p.active)},active) where id=${req.params.rateId}::uuid and store_id=${req.storeId}::uuid returning *`;if(!rows.length)return res.status(404).json({error:"Tarifa no encontrada"});res.json({rate:rows[0]})});
storesRouter.delete("/:storeId/shipping/rates/:rateId",requireStore,requirePermission("shipping.manage"),async(req,res)=>{const rows=await sql`delete from shipping_rates where id=${req.params.rateId}::uuid and store_id=${req.storeId}::uuid returning id`;if(!rows.length)return res.status(404).json({error:"Tarifa no encontrada"});res.status(204).end()});
storesRouter.get("/:storeId/taxes",requireStore,requirePermission("tax.read"),async(req,res)=>{const rows=await sql`select * from store_tax_settings where store_id=${req.storeId}::uuid`;res.json({tax:rows[0]||{enabled:false,prices_include_tax:true,default_rate:0}})});
storesRouter.put("/:storeId/taxes",requireStore,requirePermission("tax.manage"),async(req,res)=>{const rate=Number(req.body?.default_rate||0);if(!Number.isFinite(rate)||rate<0||rate>100)return res.status(400).json({error:"Impuesto inválido"});const rows=await sql`insert into store_tax_settings(store_id,enabled,prices_include_tax,default_rate) values(${req.storeId}::uuid,${Boolean(req.body?.enabled)},${req.body?.prices_include_tax!==false},${rate}) on conflict(store_id) do update set enabled=excluded.enabled,prices_include_tax=excluded.prices_include_tax,default_rate=excluded.default_rate,updated_at=now() returning *`;res.json({tax:rows[0]})});
storesRouter.post("/:storeId/access-codes/redeem",codeRedemptionLimiter,requireStore,requirePermission("billing.manage"),async(req,res)=>{const code=String(req.body?.code||"").trim().toUpperCase();if(!code)return res.status(400).json({error:"Escribe un código"});const rows=await sql`select bravoshop_redeem_access_code(${code},${req.storeId}::uuid,${req.user.id}::uuid) as result`;const result=rows[0]?.result;if(!result?.ok){const reason=result?.error;const map={invalid:[404,"Código no válido, caducado o sin usos disponibles"],already_redeemed:[409,"Esta tienda ya utilizó este código"],unsupported:[400,"Tipo de código no compatible"]};const[status,message]=map[reason]||[400,"No se pudo canjear el código"];return res.status(status).json({error:message})}res.json({ok:true,grant_type:result.grant_type,feature_key:result.feature_key,permanent:result.permanent})});
storesRouter.get("/:storeId/entitlements",requireStore,requirePermission("billing.read"),async(req,res)=>{const rows=await sql`select feature_key,permanent,ends_at,limits,source from store_feature_entitlements where store_id=${req.storeId}::uuid and (permanent=true or ends_at is null or ends_at>now())`;res.json({entitlements:rows})});

storesRouter.get("/:storeId/features/effective",requireStore,requirePermission("store.read"),async(req,res)=>{const configured=await sql`select feature_key from store_features where store_id=${req.storeId}::uuid and enabled=true`;const plan=await sql`select p.slug,p.name,pf.feature_key from store_subscriptions ss join plans p on p.id=ss.plan_id left join plan_features pf on pf.plan_id=p.id and pf.enabled=true where ss.store_id=${req.storeId}::uuid and ss.status in ('active','trialing') and (ss.complimentary_reason is null or ss.complimentary_until is null or ss.complimentary_until>now())`;const granted=await sql`select feature_key,permanent,ends_at,limits from store_feature_entitlements where store_id=${req.storeId}::uuid and (permanent=true or ends_at is null or ends_at>now())`;const ai=new Set(["ai_assistant","ai_images","image_analysis"]);const planKeys=plan.map(x=>x.feature_key).filter(Boolean);const ordinary=configured.map(x=>x.feature_key).filter(x=>!ai.has(x));const keys=[...new Set([...ordinary,...planKeys,...granted.map(x=>x.feature_key)])];res.json({features:keys,plan:plan[0]?{slug:plan[0].slug,name:plan[0].name}:null,entitlements:granted})});
