import React,{useEffect,useState}from"react";
import{MediaLibrary}from"../media/MediaLibrary.jsx";
import{listBlogPosts,saveBlogPost,deleteBlogPost}from"../data/blogService.js";
const slugify=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const draft=()=>({title:"",slug:"",excerpt:"",content:"",status:"draft",cover_media_id:null,cover_url:""});
export function BlogManager({store}){
 const[posts,setPosts]=useState([]),[editing,setEditing]=useState(null),[mediaOpen,setMediaOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=()=>listBlogPosts(store.id).then(setPosts).catch(e=>setError(e.message));
 useEffect(()=>{load()},[store.id]);
 const save=async status=>{setBusy(true);setError("");try{
 await saveBlogPost(store.id,{...editing,status});setEditing(null);setNotice(status==="published"?"Artículo publicado":"Borrador guardado");await load()
 }catch(e){setError(e.message)}finally{setBusy(false)}};
 const remove=async p=>{if(!window.confirm("¿Eliminar el artículo "+p.title+"?"))return;setError("");try{await deleteBlogPost(store.id,p.id);await load()}catch(e){setError(e.message)}};
 if(editing)return <section className="blogEditorPage"><div className="pageTitle"><div><button className="ghost" onClick={()=>setEditing(null)}>← Volver al blog</button><small>EDITORIAL</small><h1>{editing.id?"Editar artículo":"Nuevo artículo"}</h1></div><div className="quickActions"><button disabled={busy||!editing.title||!editing.slug} className="ghost" onClick={()=>save("draft")}>Guardar borrador</button><button disabled={busy||!editing.title||!editing.slug} onClick={()=>save("published")}>{busy?"Guardando…":"Publicar artículo"}</button></div></div>{error&&<div className="errorBox">{error}</div>}
 <div className="controlGrid"><article className="panel formStack"><h3>Contenido del artículo</h3><label>Título<input maxLength="180" value={editing.title||""} onChange={e=>setEditing(p=>({...p,title:e.target.value,slug:!p.id?slugify(e.target.value):p.slug}))}/></label><label>URL amigable<input maxLength="120" value={editing.slug||""} onChange={e=>setEditing(p=>({...p,slug:slugify(e.target.value)}))}/></label><label>Resumen<textarea maxLength="600" rows="3" value={editing.excerpt||""} onChange={e=>setEditing(p=>({...p,excerpt:e.target.value}))}/></label><label>Contenido<textarea maxLength="20000" rows="16" value={editing.content||""} onChange={e=>setEditing(p=>({...p,content:e.target.value}))} placeholder="Escribe el artículo. Los párrafos se conservan y se muestran como texto seguro."/></label><small>Los artículos se publican por tienda. El texto se muestra de forma segura, sin ejecutar HTML.</small></article>
 <article className="panel formStack"><h3>Portada y publicación</h3>{editing.cover_url&&<img className="blogEditorCover" src={editing.cover_url} alt="Portada seleccionada"/>}<button className="ghost" onClick={()=>setMediaOpen(true)}>Elegir imagen de la biblioteca</button>{editing.cover_media_id&&<button className="ghost" onClick={()=>setEditing(p=>({...p,cover_media_id:null,cover_url:""}))}>Quitar portada</button>}<p>Estado: <b>{editing.status==="published"?"Publicado":"Borrador"}</b></p>{editing.id&&editing.status==="published"&&<a href={"https://"+store.slug+".bravoshop.online/blog/"+encodeURIComponent(editing.slug)} target="_blank" rel="noopener noreferrer">Abrir artículo público ↗</a>}</article></div>
 {mediaOpen&&<div className="modal"><MediaLibrary storeId={store.id} onPick={asset=>{setEditing(p=>({...p,cover_media_id:asset.id,cover_url:asset.public_url||asset.url||""}));setMediaOpen(false)}} onClose={()=>setMediaOpen(false)}/></div>}</section>;
 return <section className="blogAdmin"><div className="pageTitle"><div><small>CONTENIDO</small><h1>Blog de la tienda</h1><p>Publicaciones independientes, guías, novedades y contenido de marca.</p></div><button onClick={()=>{setError("");setEditing(draft())}}>+ Nuevo artículo</button></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="successBox">{notice}</div>}
 <article className="panel">{posts.length?posts.map(p=><div className="health" key={p.id}><div><b>{p.title}</b><small>/{p.slug} · {p.status==="published"?"Publicado":"Borrador"} · {new Date(p.created_at).toLocaleDateString()}</small></div><div className="quickActions"><button className="ghost" onClick={()=>setEditing(p)}>Editar</button><button className="ghost danger" onClick={()=>remove(p)}>Eliminar</button></div></div>):<div className="empty">Todavía no hay artículos. Publica la primera guía, noticia o historia de tu marca.</div>}</article></section>
}
