import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,Crown,Search,UserRoundCheck,Users}from"lucide-react";
import{getCustomer,listCustomers,updateCustomer}from"../data/commerceService.js";import{ExportCsvButton}from"./ExportCsvButton.jsx";

const daysSince=value=>value?Math.floor((Date.now()-new Date(value).getTime())/86400000):Infinity;
function segment(c,avgValue=0){const orders=Number(c.order_count||0),value=Number(c.lifetime_value||0),days=daysSince(c.last_order_at);if(value>0&&value>=Math.max(avgValue*2,150))return"vip";if(orders>=2&&days<=180)return"repeat";if(orders===1&&days<=60)return"new";if(orders>0&&days>180)return"inactive";return"lead"}
const segmentLabel={all:"Todos",vip:"VIP",repeat:"Recurrentes",new:"Nuevos",inactive:"Inactivos",lead:"Sin compra reciente"};

export function CustomersManager({storeId,canEdit=false}){
 const[items,setItems]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>storeId&&listCustomers(storeId).then(setItems).catch(e=>setError(e.message));useEffect(()=>{load()},[storeId]);
 const avgValue=useMemo(()=>items.length?items.reduce((n,c)=>n+Number(c.lifetime_value||0),0)/items.length:0,[items]);
 const enriched=useMemo(()=>items.map(c=>({...c,segment:segment(c,avgValue)})),[items,avgValue]);
 const shown=useMemo(()=>enriched.filter(c=>(filter==="all"||c.segment===filter)&&(!query||[c.name,c.email,c.phone].join(" ").toLowerCase().includes(query.toLowerCase()))),[enriched,query,filter]);
 const metrics=useMemo(()=>({total:items.length,vip:enriched.filter(x=>x.segment==="vip").length,repeat:enriched.filter(x=>x.segment==="repeat").length,value:items.reduce((n,c)=>n+Number(c.lifetime_value||0),0)}),[items,enriched]);
 const open=async id=>{setError("");setNotice("");try{setSelected(await getCustomer(storeId,id))}catch(e){setError(e.message)}};
 const save=async()=>{if(!canEdit)return;setSaving(true);setError("");setNotice("");try{const updated=await updateCustomer(storeId,selected.id,{name:selected.name,phone:selected.phone,notes:selected.notes});setSelected({...selected,...updated});setNotice("Cliente actualizado");load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 if(selected)return <CustomerDetail customer={selected} setCustomer={setSelected} onBack={()=>setSelected(null)} onSave={save} saving={saving} canEdit={canEdit} error={error} notice={notice} avgValue={avgValue}/>;
 return <section className="crmWorkspace"><div className="pageTitle"><div><small>RELACIONES</small><h1>Clientes</h1><p>Segmenta compradores y conserva contexto útil para atenderlos mejor.</p></div><ExportCsvButton storeId={storeId} kind="customers"/></div>
 <div className="crmMetrics"><Metric label="Clientes" value={metrics.total}/><Metric label="VIP" value={metrics.vip} icon={<Crown size={17}/>}/><Metric label="Recurrentes" value={metrics.repeat} icon={<UserRoundCheck size={17}/>}/><Metric label="Valor acumulado" value={money(metrics.value)}/></div>
 {error&&<div className="errorBox">{error}</div>}<div className="catalogToolbar crmToolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, email o teléfono…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries(segmentLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 <div className="productTable"><div className="tableHead customerProCols"><span>Cliente</span><span>Segmento</span><span>Pedidos</span><span>Valor</span><span>Último pedido</span></div>{shown.map(c=><button className="productRow customerProCols" key={c.id} onClick={()=>open(c.id)}><div><b>{c.name||"Sin nombre"}</b><small>{c.email||"—"}</small></div><span className={"crmSegment "+c.segment}>{segmentLabel[c.segment]}</span><span>{c.order_count||0}</span><strong>{money(c.lifetime_value)}</strong><span>{c.last_order_at?new Date(c.last_order_at).toLocaleDateString():"—"}</span></button>)}{!shown.length&&<div className="empty"><Users/><p>No hay clientes que coincidan.</p></div>}</div></section>
}
function CustomerDetail({customer,setCustomer,onBack,onSave,saving,canEdit,error,notice,avgValue}){
 const orders=customer.orders||[],paid=orders.filter(o=>["paid","partially_refunded"].includes(o.payment_status)),spent=paid.reduce((n,o)=>n+Math.max(0,Number(o.total||0)-Number(o.refunded_total||0)),0),last=orders[0]?.created_at;
 const profile={...customer,order_count:orders.length,lifetime_value:spent,last_order_at:last};const seg=segment(profile,avgValue);
 return <section className="customerWorkspace"><div className="pageTitle"><div><button className="textBack" onClick={onBack}><ArrowLeft size={15}/> Clientes</button><small>CLIENTE</small><h1>{customer.name||customer.email||"Cliente"}</h1><div className={"crmSegment "+seg}>{segmentLabel[seg]}</div></div>{canEdit&&<button disabled={saving} onClick={onSave}>{saving?"Guardando…":"Guardar cliente"}</button>}</div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="successBox">{notice}</div>}
 <div className="customerDetailGrid"><aside className="panel formStack"><h3>Perfil y contexto</h3><label>Nombre<input disabled={!canEdit} value={customer.name||""} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>Email<input value={customer.email||""} disabled/></label><label>Teléfono<input disabled={!canEdit} value={customer.phone||""} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Notas internas<textarea disabled={!canEdit} rows="8" value={customer.notes||""} onChange={e=>setCustomer({...customer,notes:e.target.value})} placeholder="Preferencias, incidencias, necesidades o contexto útil para el equipo."/></label><small className="muted">Las notas son internas y no se muestran al cliente.</small></aside>
 <div className="customerDetailMain"><section className="metricGrid compact"><div><small>PEDIDOS</small><strong>{orders.length}</strong></div><div><small>VALOR CLIENTE</small><strong>{money(spent,orders[0]?.currency)}</strong></div><div><small>ÚLTIMA COMPRA</small><strong>{last?new Date(last).toLocaleDateString():"—"}</strong></div><div><small>CLIENTE DESDE</small><strong>{customer.created_at?new Date(customer.created_at).toLocaleDateString():"—"}</strong></div></section>
 <article className="panel"><div className="panelTitle"><div><small>HISTORIAL</small><h3>Pedidos del cliente</h3></div></div>{orders.length?<div className="customerOrdersPro">{orders.map(o=><div key={o.id}><b>#{o.id.slice(0,8)}</b><span>{new Date(o.created_at).toLocaleDateString()}</span><span className={"orderPill "+o.payment_status}>{o.payment_status}</span><span>{o.fulfillment_status||"pendiente"}</span><strong>{money(o.total,o.currency)}</strong></div>)}</div>:<div className="empty">Este cliente todavía no tiene pedidos asociados.</div>}</article>
 <article className="panel"><div className="panelTitle"><div><small>LECTURA DEL CLIENTE</small><h3>Segmentación automática</h3></div></div><p>{seg==="vip"?"Cliente de alto valor. Conviene priorizar fidelización y atención.":seg==="repeat"?"Ha comprado varias veces recientemente: buen candidato para fidelización.":seg==="new"?"Primera compra reciente: momento ideal para una buena experiencia postventa.":seg==="inactive"?"Compró anteriormente pero lleva más de 180 días sin volver.":"Todavía no tiene suficiente actividad de compra para segmentarlo."}</p><small className="muted">El segmento se calcula con pedidos, gasto acumulado y recencia; no modifica los datos del cliente.</small></article></div></div></section>
}
function Metric({label,value,icon}){return <article><div>{icon}<small>{label}</small></div><strong>{value}</strong></article>}
function money(value,currency="EUR"){try{return new Intl.NumberFormat("es-ES",{style:"currency",currency:currency||"EUR"}).format(Number(value||0))}catch{return (currency||"EUR")+" "+Number(value||0).toFixed(2)}}
