import React,{useEffect,useMemo,useState}from"react";
import{AlertTriangle,Boxes,CheckCircle2,Save,Search}from"lucide-react";
import{listInventory}from"../data/adminService.js";import{setInventory}from"../data/catalogService.js";

const available=i=>Math.max(0,Number(i.quantity||0)-Number(i.reserved||0));
export function InventoryManager({storeId}){
 const[items,setItems]=useState([]),[drafts,setDrafts]=useState({}),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[sort,setSort]=useState("risk"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(null);
 const load=()=>storeId&&listInventory(storeId).then(rows=>{setItems(rows);setDrafts(Object.fromEntries(rows.map(i=>[i.variant_id,String(i.quantity??0)])))}).catch(e=>setError(e.message));useEffect(()=>{load()},[storeId]);
 const stats=useMemo(()=>({variants:items.length,low:items.filter(i=>i.track_inventory&&available(i)>0&&available(i)<=3).length,out:items.filter(i=>i.track_inventory&&available(i)<=0).length,available:items.reduce((n,i)=>n+available(i),0),reserved:items.reduce((n,i)=>n+Number(i.reserved||0),0)}),[items]);
 const shown=useMemo(()=>items.filter(i=>{const a=available(i),match=!query||[i.product_name,i.variant_title,i.sku].join(" ").toLowerCase().includes(query.toLowerCase());return match&&(filter==="all"||filter==="healthy"&&(!i.track_inventory||a>3)||filter==="low"&&i.track_inventory&&a>0&&a<=3||filter==="out"&&i.track_inventory&&a<=0||filter==="backorder"&&i.allow_backorder)}).sort((a,b)=>sort==="name"?String(a.product_name).localeCompare(String(b.product_name)):sort==="stock"?available(a)-available(b):(risk(a)-risk(b))),[items,query,filter,sort]);
 const persist=async(i,patch={})=>{const quantity=patch.quantity!==undefined?Number(patch.quantity):Number(drafts[i.variant_id]??i.quantity);if(!Number.isSafeInteger(quantity)||quantity<0){setError("La cantidad debe ser un número entero igual o mayor que 0.");return}const next={...i,...patch,quantity};setSaving(i.variant_id);setError("");setNotice("");try{const saved=await setInventory(storeId,i.variant_id,{quantity,track_inventory:next.track_inventory!==false,allow_backorder:Boolean(next.allow_backorder)});setItems(xs=>xs.map(x=>x.variant_id===i.variant_id?{...x,...next,...saved}:x));setDrafts(d=>({...d,[i.variant_id]:String(quantity)}));setNotice("Inventario actualizado")}catch(e){setError(e.message);load()}finally{setSaving(null)}};
 return <section className="inventoryWorkspace"><div className="pageTitle"><div><small>STOCK</small><h1>Inventario</h1><p>Existencias, reservas y disponibilidad real por variante.</p></div></div>{error&&<div className="errorBox">{error}</div>}{notice&&<div className="successBox">{notice}</div>}
 <div className="inventoryMetricGrid"><Metric label="Variantes" value={stats.variants}/><Metric label="Disponibles" value={stats.available}/><Metric label="Reservadas" value={stats.reserved}/><Metric label="Stock bajo" value={stats.low} warning={stats.low>0}/><Metric label="Agotadas" value={stats.out} warning={stats.out>0}/></div>
 <div className="inventoryToolbar pro"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, variante o SKU…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todo el inventario</option><option value="healthy">Stock saludable</option><option value="low">Stock bajo</option><option value="out">Agotado</option><option value="backorder">Venta sin stock</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="risk">Mayor urgencia</option><option value="stock">Menor stock</option><option value="name">Nombre A–Z</option></select></div>
 <div className="productTable inventoryPro"><div className="tableHead inventoryOpsCols"><span>Producto</span><span>SKU</span><span>Stock físico</span><span>Disponible</span><span>Control</span><span></span></div>{shown.map(i=>{const a=available(i),dirty=String(drafts[i.variant_id]??"")!==String(i.quantity??0);return <div className="productRow inventoryOpsCols" key={i.variant_id}><div><b>{i.product_name}</b><small>{i.variant_title||"Variante principal"}</small></div><span>{i.sku||"—"}</span><div className="stockEdit"><input className="stockInput" type="number" min="0" step="1" value={drafts[i.variant_id]??""} onChange={e=>setDrafts(d=>({...d,[i.variant_id]:e.target.value}))}/><small>{Number(i.reserved||0)} reservadas</small></div><div className={"stockHealth "+(a<=0?"danger":a<=3?"warning":"good")}>{a<=0?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>}<span><b>{a}</b><small>{a<=0?"Agotado":a<=3?"Reponer pronto":"Saludable"}</small></span></div><div className="inventorySwitches"><label><input type="checkbox" checked={i.track_inventory!==false} onChange={e=>persist(i,{track_inventory:e.target.checked})}/> Controlar</label><label><input type="checkbox" checked={Boolean(i.allow_backorder)} onChange={e=>persist(i,{allow_backorder:e.target.checked})}/> Vender sin stock</label></div><button className={dirty?"inventorySave dirty":"inventorySave"} disabled={!dirty||saving===i.variant_id} onClick={()=>persist(i)}><Save size={15}/>{saving===i.variant_id?"…":"Guardar"}</button></div>})}{!shown.length&&<div className="empty"><Boxes/><p>No hay variantes que coincidan con este filtro.</p></div>}</div></section>
}
function risk(i){if(!i.track_inventory)return 4;const a=available(i);if(a<=0)return 0;if(a<=3)return 1;if(i.allow_backorder)return 2;return 3}
function Metric({label,value,warning}){return <article className={warning?"warning":""}><small>{label}</small><strong>{value}</strong></article>}
