import React,{useEffect,useMemo,useState}from"react";
import{ArrowLeft,Box,MapPin,Search,ShoppingBag,Truck,UserRound}from"lucide-react";
import{listOrders,getOrder,updateFulfillment,requestRefund}from"../data/commerceService.js";import{ExportCsvButton}from"./ExportCsvButton.jsx";

const fulfillmentLabel={unfulfilled:"Pendiente",preparing:"Preparando",fulfilled:"Enviado",delivered:"Entregado",cancelled:"Cancelado"};
const paymentLabel={paid:"Pagado",partially_refunded:"Reembolso parcial",refunded:"Reembolsado",pending:"Pendiente",failed:"Fallido"};

export function OrdersManager({storeId,canFulfill=false,canRefund=false}){
 const[items,setItems]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[refund,setRefund]=useState({amount:"",reason:"",items:{}}),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false);
 const load=()=>storeId&&listOrders(storeId).then(setItems).catch(e=>setError(e.message));
 useEffect(()=>{load()},[storeId]);
 const open=async id=>{setError("");try{setSelected(await getOrder(storeId,id))}catch(e){setError(e.message)}};
 const save=async()=>{if(!canFulfill)return;setBusy(true);setError("");setNotice("");try{const o=await updateFulfillment(storeId,selected.id,{fulfillment_status:selected.fulfillment_status,carrier:selected.carrier,tracking_number:selected.tracking_number,tracking_url:selected.tracking_url,merchant_notes:selected.merchant_notes});setSelected({...selected,...o});setNotice("Pedido actualizado");load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const doRefund=async()=>{if(!canRefund)return;setBusy(true);setError("");setNotice("");try{const lines=Object.entries(refund.items||{}).filter(([,q])=>Number(q)>0).map(([order_item_id,quantity])=>({order_item_id,quantity:Number(quantity)}));await requestRefund(storeId,selected.id,{amount:lines.length?undefined:(refund.amount?Number(refund.amount):undefined),reason:refund.reason,items:lines.length?lines:undefined});setSelected(await getOrder(storeId,selected.id));setRefund({amount:"",reason:"",items:{}});setNotice(lines.length?"Reembolso por artículos registrado":"Solicitud de reembolso registrada")}catch(e){setError(e.message)}finally{setBusy(false)}};
 const shown=useMemo(()=>items.filter(o=>(filter==="all"||o.fulfillment_status===filter)&&(!query||[o.id,o.customer_email,o.customer_name,o.tracking_number].join(" ").toLowerCase().includes(query.toLowerCase()))),[items,query,filter]);
 const metrics=useMemo(()=>({total:items.length,pending:items.filter(x=>["unfulfilled","preparing"].includes(x.fulfillment_status)).length,shipping:items.filter(x=>x.fulfillment_status==="fulfilled").length,delivered:items.filter(x=>x.fulfillment_status==="delivered").length}),[items]);
 if(selected)return <OrderDetail order={selected} setOrder={setSelected} onBack={()=>{setSelected(null);setNotice("");setError("")}} onSave={save} onRefund={doRefund} refund={refund} setRefund={setRefund} canFulfill={canFulfill} canRefund={canRefund} busy={busy} error={error} notice={notice}/>;
 return <section className="ordersWorkspace"><div className="pageTitle"><div><small>VENTAS</small><h1>Pedidos</h1><p>Gestiona preparación, entrega, seguimiento y atención postventa.</p></div><ExportCsvButton storeId={storeId} kind="orders"/></div>
 <div className="orderMetrics"><Metric label="Pedidos" value={metrics.total}/><Metric label="Por preparar" value={metrics.pending}/><Metric label="En tránsito" value={metrics.shipping}/><Metric label="Entregados" value={metrics.delivered}/></div>
 {error&&<div className="errorBox">{error}</div>}
 <div className="orderToolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pedido, cliente o seguimiento…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos los estados</option><option value="unfulfilled">Pendientes</option><option value="preparing">Preparando</option><option value="fulfilled">Enviados</option><option value="delivered">Entregados</option><option value="cancelled">Cancelados</option></select></div>
 <div className="productTable orderTablePro"><div className="tableHead orderColsPro"><span>Pedido / cliente</span><span>Estado</span><span>Fecha</span><span>Total</span></div>{shown.map(o=><button className="productRow orderColsPro" key={o.id} onClick={()=>open(o.id)}><div><b>#{o.id.slice(0,8)}</b><small>{o.customer_email||"Cliente sin email"}</small></div><div className="orderStatusStack"><span className={"orderPill "+o.payment_status}>{paymentLabel[o.payment_status]||o.payment_status}</span><span>{fulfillmentLabel[o.fulfillment_status]||o.fulfillment_status}</span></div><span>{o.created_at?new Date(o.created_at).toLocaleDateString():"—"}</span><strong>{money(o.total,o.currency)}</strong></button>)}{!shown.length&&<div className="empty"><ShoppingBag/><p>No hay pedidos que coincidan.</p></div>}</div></section>
}

function OrderDetail({order,setOrder,onBack,onSave,onRefund,refund,setRefund,canFulfill,canRefund,busy,error,notice}){
 const address=order.shipping_address||{};
 const subtotal=Number(order.subtotal||0),shipping=Number(order.shipping_total||0),tax=Number(order.tax_total||0),discount=Number(order.discount_total||0);
 return <section className="orderDetailWorkspace"><div className="pageTitle"><div><button className="textBack" onClick={onBack}><ArrowLeft size={15}/> Pedidos</button><small>PEDIDO</small><h1>#{order.id.slice(0,8)}</h1><p>{order.created_at?new Date(order.created_at).toLocaleString():""} · {paymentLabel[order.payment_status]||order.payment_status}</p></div><div className="orderDetailActions"><span className={"orderPill "+order.payment_status}>{paymentLabel[order.payment_status]||order.payment_status}</span>{canFulfill&&<button disabled={busy} onClick={onSave}>{busy?"Guardando…":"Guardar cambios"}</button>}</div></div>
 {error&&<div className="errorBox">{error}</div>}{notice&&<div className="successBox">{notice}</div>}
 <div className="orderDetailGrid"><div className="orderDetailMain">
 <article className="panel"><div className="panelTitle"><div><small>ARTÍCULOS</small><h3>Contenido del pedido</h3></div><Box size={20}/></div><div className="orderItemsPro">{(order.items||[]).map(x=><div key={x.id}><div><b>{x.title}</b><small>{x.sku||"Sin SKU"} · Cantidad {x.quantity}{Number(x.refunded_quantity||0)>0?" · "+x.refunded_quantity+" reembolsadas":""}</small></div><span>{x.quantity} × {money(x.unit_price,order.currency)}</span><strong>{money(x.total??Number(x.unit_price)*Number(x.quantity),order.currency)}</strong></div>)}</div><div className="orderTotals"><span>Subtotal <b>{money(subtotal,order.currency)}</b></span>{discount>0&&<span>Descuento <b>-{money(discount,order.currency)}</b></span>}<span>Envío <b>{money(shipping,order.currency)}</b></span><span>Impuestos <b>{money(tax,order.currency)}</b></span><strong>Total <b>{money(order.total,order.currency)}</b></strong></div></article>
 <article className="panel"><div className="panelTitle"><div><small>LOGÍSTICA</small><h3>Preparación y seguimiento</h3></div><Truck size={20}/></div>{order.shipping_method&&<div className="shippingMethodBadge"><small>MÉTODO ELEGIDO</small><b>{order.shipping_method}</b><span>{money(order.shipping_total,order.currency)}</span></div>}<div className="orderFulfillmentGrid"><label>Estado<select disabled={!canFulfill} value={order.fulfillment_status||"unfulfilled"} onChange={e=>setOrder({...order,fulfillment_status:e.target.value})}><option value="unfulfilled">Pendiente</option><option value="preparing">Preparando</option><option value="fulfilled">Enviado</option><option value="delivered">Entregado</option><option value="cancelled">Cancelado</option></select></label><label>Transportista<input disabled={!canFulfill} value={order.carrier||""} onChange={e=>setOrder({...order,carrier:e.target.value})} placeholder="Correos, SEUR, DHL…"/></label><label>Número de seguimiento<input disabled={!canFulfill} value={order.tracking_number||""} onChange={e=>setOrder({...order,tracking_number:e.target.value})}/></label><label>URL de seguimiento<input disabled={!canFulfill} value={order.tracking_url||""} onChange={e=>setOrder({...order,tracking_url:e.target.value})}/></label></div><label className="orderNotes">Notas internas<textarea disabled={!canFulfill} rows="3" value={order.merchant_notes||""} onChange={e=>setOrder({...order,merchant_notes:e.target.value})} placeholder="Solo visibles para el equipo de la tienda."/></label></article>
 <article className="panel"><div className="panelTitle"><div><small>ACTIVIDAD</small><h3>Historial del pedido</h3></div></div><div className="orderTimeline">{(order.events||[]).length?(order.events||[]).map((x,i)=><div key={i}><i/><span><b>{x.message||x.event_type}</b><small>{new Date(x.created_at).toLocaleString()}</small></span></div>):<p className="muted">Todavía no hay eventos registrados.</p>}</div></article>
 </div><aside className="orderDetailSide">
 <article className="panel"><div className="panelTitle"><div><small>CLIENTE</small><h3>Contacto</h3></div><UserRound size={19}/></div><p><b>{order.customer_name||address.name||"Cliente"}</b></p><p>{order.customer_email||"Sin email"}</p>{order.customer_phone&&<p>{order.customer_phone}</p>}</article>
 <article className="panel"><div className="panelTitle"><div><small>ENTREGA</small><h3>Dirección</h3></div><MapPin size={19}/></div>{order.shipping_method&&<p><b>Método:</b> {order.shipping_method}</p>}{address.line1||address.city?<address>{address.name&&<b>{address.name}</b>}<span>{address.line1}</span>{address.line2&&<span>{address.line2}</span>}<span>{[address.postal_code,address.city].filter(Boolean).join(" ")}</span><span>{[address.region,address.country].filter(Boolean).join(", ")}</span>{address.phone&&<span>{address.phone}</span>}</address>:<p className="muted">Sin dirección registrada.</p>}</article>
 <article className="panel formStack"><small>REEMBOLSO</small><h3>Postventa</h3>{canRefund&&(["paid","partially_refunded"].includes(order.payment_status)?<><div className="refundItems"><small>Selecciona artículos (opcional)</small>{(order.items||[]).map(x=><label key={x.id}><span>{x.title}</span><input type="number" min="0" max={Math.max(0,Number(x.quantity)-Number(x.refunded_quantity||0))} step="1" value={refund.items?.[x.id]??0} onChange={e=>{const available=Math.max(0,Number(x.quantity)-Number(x.refunded_quantity||0));setRefund({...refund,items:{...(refund.items||{}),[x.id]:Math.max(0,Math.min(available,Number(e.target.value)||0))}})}}/><small>de {Math.max(0,Number(x.quantity)-Number(x.refunded_quantity||0))} disponibles</small></label>)}</div><label>Importe manual<input type="number" min="0.01" step="0.01" value={refund.amount} disabled={Object.values(refund.items||{}).some(q=>Number(q)>0)} onChange={e=>setRefund({...refund,amount:e.target.value})} placeholder="Vacío = restante"/></label><small className="muted">Si seleccionas artículos, BravoShop calcula automáticamente el importe respetando descuentos.</small><label>Motivo<input value={refund.reason} onChange={e=>setRefund({...refund,reason:e.target.value})}/></label><button className="ghost" disabled={busy} onClick={onRefund}>Solicitar reembolso</button></>:<p className="muted">Disponible cuando el pedido esté pagado.</p>)}{(order.refunds||[]).map(x=><div className="refundRow" key={x.id}><b>{money(x.amount,x.currency||order.currency)}</b><span>{x.status}</span></div>)}</article>
 </aside></div></section>
}
function Metric({label,value}){return <article><small>{label}</small><strong>{value}</strong></article>}
function money(value,currency="EUR"){try{return new Intl.NumberFormat("es-ES",{style:"currency",currency:currency||"EUR"}).format(Number(value||0))}catch{return (currency||"EUR")+" "+Number(value||0).toFixed(2)}}
