import React,{useState}from"react";
import{ArrowLeft,BarChart3,Box,ChevronRight,Eye,Home,LayoutDashboard,Megaphone,Package,Palette,Plus,Settings,ShoppingBag,ShoppingCart,Users}from"lucide-react";
import"./demo.css";

const seed=[
{id:1,name:"Monstera Deliciosa",price:24.90,stock:18,category:"Plantas de interior",image:"https://images.unsplash.com/photo-1614594575810-617d6e8d3a4a?auto=format&fit=crop&w=900&q=85"},
{id:2,name:"Calathea Orbifolia",price:19.90,stock:11,category:"Plantas de interior",image:"https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=85"},
{id:3,name:"Pothos Golden",price:14.90,stock:26,category:"Plantas de interior",image:"https://images.unsplash.com/photo-1616500156885-e51d834cab9b?auto=format&fit=crop&w=900&q=85"},
{id:4,name:"Zamioculca",price:22.90,stock:9,category:"Plantas resistentes",image:"https://images.unsplash.com/photo-1597055181300-e3633a207517?auto=format&fit=crop&w=900&q=85"}];

const sections={
inicio:{title:"Resumen",icon:LayoutDashboard},
productos:{title:"Productos",icon:Package},
pedidos:{title:"Pedidos",icon:ShoppingBag},
clientes:{title:"Clientes",icon:Users},
diseno:{title:"Tienda online",icon:Palette},
marketing:{title:"Marketing",icon:Megaphone},
analitica:{title:"Analíticas",icon:BarChart3},
apps:{title:"Apps",icon:Box},
config:{title:"Configuración",icon:Settings}
};

export function DemoExperience(){
 const[mode,setMode]=useState("admin"),[section,setSection]=useState("inicio"),[products,setProducts]=useState(seed),[cart,setCart]=useState([]),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[headline,setHeadline]=useState("Plantas que inspiran hogares");
 const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
 if(mode==="store")return <DemoStore products={products} cart={cart} add={add} selected={selected} setSelected={setSelected} headline={headline} onAdmin={()=>setMode("admin")}/>;
 return <div className="bdemo"><DemoTop mode={mode} onStore={()=>setMode("store")}/><div className="bdemoShell"><aside className="bdemoSide"><div className="bdemoBrand">NATURA <small>Demo</small></div>{Object.entries(sections).map(([k,v])=>{const I=v.icon;return <button key={k} className={section===k?"active":""} onClick={()=>setSection(k)}><I size={18}/>{v.title}</button>})}<button className="bdemoView" onClick={()=>setMode("store")}><Eye size={18}/>Ver tienda</button></aside><main className="bdemoMain"><AdminSection section={section} setSection={setSection} products={products} setProducts={setProducts} editing={editing} setEditing={setEditing} headline={headline} setHeadline={setHeadline}/></main></div></div>
}

function DemoTop({onStore}){return <div className="bdemoTop"><a href="/"><ArrowLeft size={17}/> Volver a BravoShop</a><span><b>DEMO INTERACTIVA</b> · Los cambios son temporales</span><button onClick={onStore}>Ver tienda <Eye size={16}/></button></div>}

function AdminSection({section,setSection,products,setProducts,editing,setEditing,headline,setHeadline}){
 if(section==="productos")return <Products products={products} setProducts={setProducts} editing={editing} setEditing={setEditing}/>;
 if(section==="diseno")return <Design headline={headline} setHeadline={setHeadline}/>;
 const data={
 inicio:["¡Buenas! 👋","Aquí tienes un resumen de tu tienda de ejemplo."],
 pedidos:["Pedidos","Consulta y gestiona los pedidos recibidos."],
 clientes:["Clientes","Conoce a tus clientes y su historial de compra."],
 marketing:["Marketing","Crea descuentos, campañas y acciones para vender más."],
 analitica:["Analíticas","Entiende qué vende, de dónde llegan tus visitas y cómo creces."],
 apps:["Apps","Amplía tu tienda con herramientas y conexiones."],
 config:["Configuración","Gestiona pagos, envíos, dominios, impuestos y preferencias."]
 }[section]||["BravoShop","Demo"];
 return <><div className="bdemoHeading"><div><small>TIENDA DEMO</small><h1>{data[0]}</h1><p>{data[1]}</p></div><button className="primary" onClick={()=>setSection(section==="inicio"?"productos":"inicio")}>{section==="inicio"?"Gestionar productos":"Volver al resumen"}</button></div>{section==="inicio"?<Dashboard products={products} onViewAll={()=>setSection("productos")}/>:<Generic section={section}/>}</>
}

function Dashboard({products,onViewAll}){return <><div className="bdemoStats"><article><small>Ventas</small><b>€1.248</b><em>↑ 12%</em></article><article><small>Pedidos</small><b>56</b><em>↑ 8%</em></article><article><small>Visitas</small><b>342</b><em>↑ 24%</em></article><article><small>Clientes</small><b>28</b><em>↑ 16%</em></article></div><div className="bdemoCard"><div className="cardTitle"><h2>Ventas</h2><span>Últimos 30 días</span></div><div className="fakeChart"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="bdemoCard"><div className="cardTitle"><h2>Productos recientes</h2><button onClick={onViewAll}>Ver todos</button></div>{products.slice(0,4).map(p=><div className="demoRow" key={p.id}><img src={p.image}/><b>{p.name}</b><span>En stock · {p.stock}</span><strong>€{p.price.toFixed(2)}</strong></div>)}</div></>}

function Products({products,setProducts,editing,setEditing}){
 const create=()=>setEditing({id:Date.now(),name:"",price:19.90,stock:10,category:"Plantas de interior",image:"https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=85"});
 if(editing)return <ProductEditor product={editing} onCancel={()=>setEditing(null)} onSave={p=>{setProducts(x=>x.some(i=>i.id===p.id)?x.map(i=>i.id===p.id?p:i):[p,...x]);setEditing(null)}}/>;
 return <><div className="bdemoHeading"><div><small>CATÁLOGO</small><h1>Productos</h1><p>Crea, edita, organiza y publica los productos de tu tienda.</p></div><button className="primary" onClick={create}><Plus size={17}/>Añadir producto</button></div><div className="bdemoCard"><div className="demoTableHead"><span>Producto</span><span>Inventario</span><span>Precio</span><span/></div>{products.map(p=><div className="demoProductRow" key={p.id}><div><img src={p.image}/><span><b>{p.name}</b><small>{p.category}</small></span></div><span>{p.stock} disponibles</span><strong>€{p.price.toFixed(2)}</strong><button onClick={()=>setEditing({...p})}>Editar</button></div>)}</div></>}

function ProductEditor({product,onSave,onCancel}){const[p,setP]=useState(product);return <><div className="bdemoHeading"><div><small>PRODUCTOS / EDITAR</small><h1>{p.name||"Nuevo producto"}</h1><p>Prueba el editor. Al guardar, el producto aparecerá en la tienda demo.</p></div><div className="headActions"><button onClick={onCancel}>Cancelar</button><button className="primary" onClick={()=>onSave({...p,name:p.name.trim()||"Producto sin nombre"})}>Guardar</button></div></div><div className="editorGrid"><section className="bdemoCard formCard"><h2>Información</h2><label>Nombre del producto<input value={p.name} onChange={e=>setP({...p,name:e.target.value})} placeholder="Ej. Alocasia Frydek"/></label><label>Descripción<textarea placeholder="Describe tu producto..."/></label><label>Categoría<select value={p.category} onChange={e=>setP({...p,category:e.target.value})}><option>Plantas de interior</option><option>Plantas resistentes</option><option>Macetas</option><option>Decoración</option></select></label></section><aside className="bdemoCard formCard"><h2>Precio e inventario</h2><label>Precio (€)<input type="number" min="0" step=".01" value={p.price} onChange={e=>setP({...p,price:Number(e.target.value)||0})}/></label><label>Stock<input type="number" min="0" value={p.stock} onChange={e=>setP({...p,stock:Number(e.target.value)||0})}/></label><div className="demoNotice">Modo demostración: nada se cobra ni se guarda permanentemente.</div></aside></div></>}

function Design({headline,setHeadline}){const[tool,setTool]=useState("Banner principal"),[saved,setSaved]=useState(false),[extra,setExtra]=useState([]);const publish=()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)};const addSection=()=>setExtra(x=>[...x,"Sección "+(x.length+1)]);return <><div className="bdemoHeading"><div><small>TIENDA ONLINE</small><h1>Editor visual</h1><p>Personaliza la apariencia de tu tienda y mira los cambios al instante.</p></div><button className="primary" onClick={publish}>{saved?"Cambios publicados ✓":"Publicar cambios"}</button></div><div className="designGrid"><div className="designTools bdemoCard"><h3>Personalizar tema</h3>{["Colores","Tipografías","Cabecera","Banner principal","Secciones","Productos destacados","Categorías","Pie de página"].map(x=><button key={x} className={tool===x?"active":""} onClick={()=>setTool(x)}>{x}<ChevronRight size={15}/></button>)}<div className="demoToolState"><small>EDITANDO</small><b>{tool}</b><span>Los controles de esta demo cambian el contenido temporal de la vista previa.</span></div></div><div className="designPreview"><div className="previewNav">NATURA <span>Plantas　Macetas　Decoración　Regalos</span></div><div className="previewHero"><div><small>VIVE VERDE</small><h2>{headline}</h2><span className="demoPreviewCta">Descubrir colección</span></div></div><div className="inlineEdit"><label>Texto del banner<input value={headline} onChange={e=>setHeadline(e.target.value)}/></label></div><div className="previewSections"><div>Banner principal</div><div>Categorías</div><div>Productos destacados</div>{extra.map(x=><div key={x}>{x}</div>)}<button onClick={addSection}><Plus/> Añadir sección</button></div></div></div></>}

function Generic({section}){const[selected,setSelected]=useState("");const blocks={pedidos:["#1056 · Laura M.","€54,80 · Pagado","#1055 · Carlos R.","€29,90 · Preparando","#1054 · Ana P.","€78,40 · Enviado"],clientes:["Laura Martínez","3 pedidos · €142,60","Carlos Ruiz","2 pedidos · €89,90","Ana Pérez","5 pedidos · €264,30"],marketing:["Código BIENVENIDA10","10% de descuento · Activo","Envío gratis +50€","Automático · Activo","Carrito abandonado","Automatización · Demo"],analitica:["Conversión","3,8%","Ticket medio","€42,60","Productos vendidos","87"],apps:["Pagos","Conectado en demo","Email marketing","Disponible","Reseñas","Disponible"],config:["Pagos y cobros","Configurar","Envíos y entrega","Configurar","Dominio","demo.bravoshop.online"]};const a=blocks[section]||[];return <><div className="bdemoCard genericGrid">{a.map((x,i)=>i%2===0?<div key={x}><b>{x}</b><span>{a[i+1]}</span><button onClick={()=>setSelected(x)}>Abrir <ChevronRight size={14}/></button></div>:null)}</div>{selected&&<div className="demoModuleDetail"><b>{selected}</b><span>Vista interactiva de ejemplo. En una tienda real aquí se abriría la gestión completa del módulo.</span><button onClick={()=>setSelected("")}>Cerrar</button></div>}</>}

function DemoStore({products,cart,add,selected,setSelected,headline,onAdmin}){const[showCart,setShowCart]=useState(false),[checkoutMsg,setCheckoutMsg]=useState("");const total=cart.reduce((s,p)=>s+p.price*p.qty,0);return <div className="demoStore"><div className="storeDemoBar"><a href="/"><ArrowLeft size={16}/> BravoShop</a><span>Estás viendo una tienda de demostración</span><button onClick={onAdmin}>Administrar demo</button></div><header className="storeNav"><b>NATURA</b><nav>Plantas　Macetas　Decoración　Jardinería　Regalos</nav><button onClick={()=>setShowCart(!showCart)}><ShoppingCart size={20}/><i>{cart.reduce((s,p)=>s+p.qty,0)}</i></button></header>{showCart&&<div className="cartDrawer"><h2>Tu carrito</h2>{cart.length?cart.map(p=><div key={p.id}><span>{p.name} × {p.qty}</span><b>€{(p.price*p.qty).toFixed(2)}</b></div>):<p>Tu carrito está vacío.</p>}<hr/><strong>Total €{total.toFixed(2)}</strong><button onClick={()=>setCheckoutMsg("Checkout de demostración: aquí se abriría el pago seguro, pero no se realizará ningún cobro.")}>Finalizar compra</button>{checkoutMsg&&<p className="demoCheckoutNote">{checkoutMsg}</p>}</div>}{selected?<ProductPage p={selected} add={add} back={()=>setSelected(null)}/>:<><section className="storeHero"><div><small>NATURALEZA EN CASA</small><h1>{headline}</h1><p>Plantas seleccionadas para convertir cualquier rincón en un lugar especial.</p><button onClick={()=>document.getElementById("demo-products")?.scrollIntoView({behavior:"smooth"})}>Descubrir plantas</button></div></section><div className="storeBenefits"><span>🚚 Envío 24–72h</span><span>🌿 Plantas seleccionadas</span><span>🔒 Pago seguro</span><span>💬 Atención personalizada</span></div><section className="storeProducts" id="demo-products"><div><small>SELECCIÓN NATURA</small><h2>Productos destacados</h2></div><div className="productGrid">{products.map(p=><article key={p.id}><button className="productImage" onClick={()=>setSelected(p)}><img src={p.image}/></button><small>{p.category}</small><h3>{p.name}</h3><div><b>€{p.price.toFixed(2)}</b><button onClick={()=>add(p)}>Añadir</button></div></article>)}</div></section></>}</div>}

function ProductPage({p,add,back}){return <main className="productPage"><button className="backProduct" onClick={back}>← Volver a plantas</button><div className="productDetail"><div className="productBig"><img src={p.image}/></div><div className="productInfo"><small>{p.category.toUpperCase()}</small><h1>{p.name}</h1><div className="stars">★★★★★ <span>(128 reseñas)</span></div><strong>€{p.price.toFixed(2)}</strong><p>Una planta especial para aportar textura, calma y vida a tu hogar. Seleccionada con cuidado y preparada para disfrutar desde el primer día.</p><label>Tamaño<select><option>S</option><option>M</option><option>L</option></select></label><button className="buy" onClick={()=>add(p)}>Añadir al carrito</button><details open><summary>Cuidados</summary><p>Luz indirecta · Riego moderado · Interior.</p></details><details><summary>Envíos y devoluciones</summary><p>Entrega estimada 24–72h. Demo ilustrativa.</p></details></div></div></main>}
