create extension if not exists pgcrypto;
create table organizations(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table stores(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id) on delete cascade,name text not null,slug text not null unique,sector text,status text not null default 'trial',created_at timestamptz not null default now());
create table store_members(store_id uuid references stores(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'owner',primary key(store_id,user_id));
create table store_settings(store_id uuid primary key references stores(id) on delete cascade,settings jsonb not null default '{}'::jsonb);
create table store_theme(store_id uuid primary key references stores(id) on delete cascade,theme jsonb not null default '{}'::jsonb);
create table products(id uuid primary key default gen_random_uuid(),store_id uuid not null references stores(id) on delete cascade,name text not null,slug text not null,description text,price numeric(12,2) not null default 0,status text not null default 'draft',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(store_id,slug));
create table customers(id uuid primary key default gen_random_uuid(),store_id uuid not null references stores(id) on delete cascade,email text,name text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table orders(id uuid primary key default gen_random_uuid(),store_id uuid not null references stores(id) on delete cascade,customer_id uuid references customers(id),status text not null default 'pending',total numeric(12,2) not null default 0,created_at timestamptz not null default now());
create table store_features(store_id uuid references stores(id) on delete cascade,feature_key text not null,enabled boolean not null default true,primary key(store_id,feature_key));
create or replace function is_store_member(target_store uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from store_members sm where sm.store_id=target_store and sm.user_id=auth.uid())$$;
alter table stores enable row level security;alter table store_members enable row level security;alter table store_settings enable row level security;alter table store_theme enable row level security;alter table products enable row level security;alter table customers enable row level security;alter table orders enable row level security;alter table store_features enable row level security;
create policy stores_member_select on stores for select to authenticated using(is_store_member(id));
create policy members_select on store_members for select to authenticated using(user_id=auth.uid() or is_store_member(store_id));
create policy settings_member_all on store_settings for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy theme_member_all on store_theme for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy products_member_all on products for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy customers_member_all on customers for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy orders_member_all on orders for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy features_member_select on store_features for select to authenticated using(is_store_member(store_id));