-- BravoShop control plane: plans, entitlements, promotions and audit
create table plans(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,status text not null default 'active',monthly_price numeric(12,2),annual_price numeric(12,2),trial_days integer not null default 0,is_public boolean not null default true,metadata jsonb not null default '{}'::jsonb);
create table plan_features(plan_id uuid references plans(id) on delete cascade,feature_key text not null,enabled boolean not null default true,limits jsonb not null default '{}'::jsonb,primary key(plan_id,feature_key));
create table store_subscriptions(store_id uuid primary key references stores(id) on delete cascade,plan_id uuid references plans(id),status text not null default 'trialing',trial_ends_at timestamptz,complimentary_until timestamptz,complimentary_reason text,provider_customer_id text,provider_subscription_id text,updated_at timestamptz not null default now());
create table promotions(id uuid primary key default gen_random_uuid(),code text not null unique,kind text not null,value numeric(12,2),free_months integer,starts_at timestamptz,ends_at timestamptz,max_uses integer,uses integer not null default 0,allowed_plan_ids uuid[] not null default '{}',active boolean not null default true,metadata jsonb not null default '{}'::jsonb);
create table platform_feature_flags(key text primary key,enabled boolean not null default false,rollout_percent integer not null default 0 check(rollout_percent between 0 and 100),config jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table platform_controls(key text primary key,enabled boolean not null default true,reason text,updated_at timestamptz not null default now());
create table audit_log(id bigint generated always as identity primary key,actor_user_id uuid references auth.users(id),store_id uuid references stores(id),action text not null,resource_type text,resource_id text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table domains(id uuid primary key default gen_random_uuid(),store_id uuid not null references stores(id) on delete cascade,hostname text not null unique,kind text not null default 'subdomain',status text not null default 'pending',verified_at timestamptz);
alter table store_subscriptions enable row level security;alter table domains enable row level security;alter table audit_log enable row level security;
create policy subscription_member_select on store_subscriptions for select to authenticated using(is_store_member(store_id));
create policy domains_member_all on domains for all to authenticated using(is_store_member(store_id)) with check(is_store_member(store_id));
create policy audit_member_select on audit_log for select to authenticated using(store_id is not null and is_store_member(store_id));
insert into platform_controls(key,enabled) values('checkout',true),('ai_assistant',true),('ai_images',true),('registrations',true),('store_creation',true),('emails',true),('automations',true) on conflict do nothing;
