import React,{useState}from"react";import{Store,ShieldCheck,Sparkles,Blocks,BarChart3,ArrowRight}from"lucide-react";import{Onboarding}from"./onboarding/Onboarding.jsx";import{MerchantAdmin}from"./admin/MerchantAdmin.jsx";import{SuperAdmin}from"./admin/SuperAdmin.jsx";import{AuthScreen}from"./auth/AuthScreen.jsx";import{useAuth}from"./auth/AuthProvider.jsx";import{createStore,listMyStores}from"./data/storeService.js";
const sectors=["Moda","Alimentación","Belleza","Tecnología","Hogar","Plantas","Servicios","Mascotas"];
export function App(){const{user,loading}=useAuth();const[view,setView]=useState("home");const[store,setStore]=useState(null);const[authMode,setAuthMode]=useState("login");const[error,setError]=useState("");
async function openMerchant(){if(!user){setAuthMode("login");setView("auth");return}setError("");try{const stores=await listMyStores();if(stores.length){setStore(stores[0]);setView("merchant")}else setView("onboarding")}catch(e){setError(e.message)}}
function startCreate(){if(!user){setAuthMode("register");setView("auth")}else setView("onboarding")}
if(loading)return <div className="bootScreen">Cargando BravoShop…</div>;
if(view==="auth")return <AuthScreen mode={authMode} onBack={()=>setView("home")} onDone={()=>authMode==="register"?setView("onboarding"):openMerchant()}/>;
if(view==="onboarding")return <Onboarding onCancel={()=>setView("home")} onFinish={async data=>{const created=await createStore({...data,theme:{template:data.template,primary_color:data.color}});setStore(created);setView("merchant")}}/>;
if(view==="merchant")return <MerchantAdmin store={store} onExit={()=>setView("home")}/>;
if(view==="super")return <SuperAdmin onExit={()=>setView("home")}/>;
return <div><header className="nav"><strong className="brand">BravoShop</strong><nav><a href="#platform">Plataforma</a><a href="#sectors">Negocios</a>{user?.role==="super_admin"&&<button className="navLink" onClick={()=>setView("super")}>Control</button>}</nav><div className="actions"><button className="ghost" onClick={openMerchant}>{user?"Mis tiendas":"Iniciar sesión"}</button><button onClick={startCreate}>Crear mi tienda</button></div></header>{error&&<div className="globalError">{error}</div>}<main><section className="hero"><div className="eyebrow">COMERCIO, A TU MANERA</div><h1>Tu negocio merece una tienda que se sienta <em>tuya.</em></h1><p>Crea, personaliza, publica y gestiona una tienda profesional desde una plataforma sencilla, potente y preparada para crecer contigo.</p><div className="heroActions"><button onClick={startCreate}>Crear mi tienda <ArrowRight size={17}/></button><button className="ghost" onClick={openMerchant}>Explorar BravoShop</button></div><div className="trust">Sin código · Plantillas por sector · IA opcional · Administración completa</div></section><section id="sectors" className="section"><div className="sectionHead"><span>UNA PLATAFORMA. MUCHOS NEGOCIOS.</span><h2>BravoShop se adapta a lo que vendes.</h2></div><div className="sectors">{sectors.map((s,i)=><article key={s}><div className={"visual v"+i}></div><h3>{s}</h3><p>Diseño, campos y herramientas adaptadas a tu sector.</p></article>)}</div></section><section id="platform" className="section dark"><div className="sectionHead"><span>EL MOTOR BRAVOSHOP</span><h2>Todo conectado. Sin complicarlo.</h2></div><div className="features"><Feature icon={<Store/>} title="Storefront" text="Tiendas rápidas, personalizables y optimizadas para móvil."/><Feature icon={<Blocks/>} title="Módulos" text="Activa solo las herramientas que cada negocio necesita."/><Feature icon={<Sparkles/>} title="IA" text="Asistencia comercial y operativa adaptada a cada tienda."/><Feature icon={<BarChart3/>} title="Administración" text="Productos, pedidos, clientes, inventario y analítica."/><Feature icon={<ShieldCheck/>} title="Multi-tenant seguro" text="Cada empresa aislada mediante permisos y políticas de datos."/></div></section></main><footer>© BravoShop · Plataforma SaaS de comercio</footer></div>}function Feature({icon,title,text}){return <article className="feature"><div>{icon}</div><h3>{title}</h3><p>{text}</p></article>}